version: "3.9"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - "./.env"

  web:
    build: .
    ports:
      - "8005:8000"
    command: >
      sh -c "sh run.sh &&
             gunicorn --bind 0.0.0.0:8000 millionaire.wsgi"
    volumes:
      - .:/app
      - media_files:/app/media/
      - static_dev:/app/static_dev/
    depends_on:
      - db
    env_file:
      - "./.env"

volumes:
  static_dev:
  media_files:
  postgres_data: